# OpenDKIM configuration
# Variables replaced by entrypoint.sh: __MAIL_DOMAIN__

Syslog          yes
LogWhy          yes
Mode            sv
Canonicalization relaxed/relaxed
Domain          __MAIL_DOMAIN__
Selector        chorus
KeyFile         /etc/opendkim/keys/__MAIL_DOMAIN__/chorus.private
Socket          inet:8891@localhost
PidFile         /run/opendkim/opendkim.pid
UMask           002
UserID          opendkim:opendkim
